[package]
name = "ts-rs"
version = "1.0.0"
authors = ["Moritz Bischof <moritz.bischof@aleph-alpha.de>"]
edition = "2018"
license = "MIT"
description = "generate typescript bindings from rust types"
homepage = "https://github.com/Aleph-Alpha/ts-rs"
repository = "https://github.com/Aleph-Alpha/ts-rs"

[features]
serde-compat = ["ts-rs-macros/serde-compat"]

[dependencies]
ts-rs-macros = { version = "1.0", path = "../macros" }